import { WIP_SOURCE, WIP_DEFINITION, wipFilters, wipMeasures, wipDefaults, wipRequest, type WipCapability, type WipRequest, type WipValues, type WipResult } from '../data/originalWorkInProgress'
export const wipRef = (n: number) => n.toString(16).toUpperCase().padStart(32, '0')
export const wipCapability: WipCapability = { Version: 1, World: 'fenix', SourceId: WIP_SOURCE, DefinitionSha256: WIP_DEFINITION,
  ModuleSha256: '34bddabf9b367769b4443c2ad1bb4f425aa3f9b8d02bba96004c35d62a0576bd', QuerySha256: '6c4f1a9dcce89113ddf44c399ea1985df1a97df7d403468c1c32417555cac368', Executable: true, DefaultRows: [...wipFilters], Filters: [...wipFilters], DefaultMeasures: [...wipDefaults], Measures: [...wipMeasures], MoneyPolicy: 'NativeStoredManagementWipNoFxConversion', QuantityPolicy: 'NativeMaterialQuantityNoUnitConversion', DatePolicy: 'InclusiveBusinessDaysThroughLastWholeSecond', AppliesFxConversion: false, ManagementCurrencyPresentationVerified: false, SourceParityVerified: false, OriginalFullTaskAccepted: false }
export const wipWire = (all = false) => wipRequest(wipCapability, '2026-09-01', '2026-09-30', { Divisions: [], ProductGroups: [], CostArticles: [] }, all ? wipMeasures : wipDefaults)
export function wipResult(request: WipRequest = wipWire()): WipResult {
  const zero = () => Object.fromEntries(request.Measures.map(m => [m, m === 'НоменклатураЗатратКоличество' ? '0.000' : '0.00'])) as WipValues
  const balance = { ...zero(), ...Object.fromEntries([['НачОст', '10.00'], ['НачОстНДС', '2.00'], ['КонОст', '8.00'], ['КонОстНДС', '1.60']].filter(([k]) => request.Measures.includes(k as typeof wipMeasures[number]))) }
  const movement = { ...zero(), ...Object.fromEntries([['Расход', '2.00'], ['РасходНДС', '0.40'], ['НоменклатураЗатратКоличество', '3.000']].filter(([k]) => request.Measures.includes(k as typeof wipMeasures[number]))) }
  const all = [{ CostArticle: null, Caption: 'Без статті', CaptionAvailable: true, Values: balance }, { CostArticle: wipRef(3), Caption: 'Наша стаття', CaptionAvailable: true, Values: movement }]
  const articles = all.filter(a => !request.CostArticles.length || request.CostArticles.includes(a.CostArticle ?? ''))
  const selected = (!request.Divisions.length || request.Divisions.includes(wipRef(1))) && (!request.ProductGroups.length || request.ProductGroups.includes(wipRef(2)))
  const values = selected ? Object.fromEntries(request.Measures.map(m => [m, articles.reduce((sum, a) => sum + BigInt(a.Values[m]!.replace('.', '')), 0n)]).map(([m, n]) => {
    const scale = m === 'НоменклатураЗатратКоличество' ? 3 : 2, raw = (n as bigint).toString().padStart(scale + 1, '0'); return [m, raw.slice(0, -scale) + '.' + raw.slice(-scale)]
  })) as WipValues : zero()
  return { ...request, ...wipCapability, From: request.From, Through: request.Through, Divisions: request.Divisions, ProductGroups: request.ProductGroups, CostArticles: request.CostArticles, Measures: request.Measures, Available: true, Code: 'original_work_in_progress_complete', NormalInputsComplete: true, OurSnapshotVerified: true, InputWitnessSha256: 'a'.repeat(64), ResultSha256: 'b'.repeat(64), Rows: selected && articles.length ? [{ Division: wipRef(1), Caption: 'Наш підрозділ', CaptionAvailable: true, Values: values, ProductGroups: [{ ProductGroup: wipRef(2), Caption: 'Наша група', CaptionAvailable: true, Values: values, Articles: articles }] }] : [], Totals: values, Choices: { Подразделение: [{ Key: wipRef(1), Caption: 'Наш підрозділ' }], НоменклатурнаяГруппа: [{ Key: wipRef(2), Caption: 'Наша група' }], СтатьяЗатрат: [{ Key: wipRef(3), Caption: 'Наша стаття' }] }, MissingCaptionMappings: [], Dependency: null }
}
