import type { ReactNode } from 'react'
import { Navigate } from 'react-router-dom'
import { ModulePage } from '../../pages/module/ModulePage'
import {
  AccountableExpensesPage,
  ActProvidingServiceDetailPage,
  ActProvidingServicesPage,
  AccountingBanksPage,
  AdvancePaymentsPage,
  AdvancedReportsPage,
  AllSadsPage,
  BasketSupplyUkraineOrderPage,
  ClientAccountingCashFlowPage,
  ClientEditPage,
  ClientNewPage,
  ClientResourcesPage,
  ClientsPage,
  ConsumableOrderFormPage,
  ConsumableOrderPayPage,
  ConsumableOrdersPage,
  ConsumableProductsPage,
  ConsumableStorageFormPage,
  ConsumableStoragesPage,
  DashboardPage,
  EditSadPage,
  EditSaleSadPage,
  EditTaxFreePackListPage,
  EditTirSadPage,
  IncomeCashflowClientFormPage,
  IncomeCashflowConversionFormPage,
  IncomeCashflowShopFormPage,
  IncomeCashflowUserFormPage,
  IncomeCashflowsPage,
  IncompleteSalesOnlineShopPage,
  NewEcommerceClientsPage,
  OnlineShopCitiesPage,
  OnlineShopClientsPage,
  OnlineShopSeoPage,
  OrganizationClientEditPage,
  OrganizationClientNewPage,
  OrganizationClientsPage,
  OrganisationServicesPage,
  OutgoingCashflowsPage,
  PaymentAccountFormPage,
  PaymentAccountsPage,
  PaymentCashflowArticleFormPage,
  DepreciatedOrdersPage,
  ProductDeliveryProtocolsPage,
  ProductDeliveryProtocolLogisticPathPage,
  ProductDeliveryProtocolSpecificationPage,
  ProductDeliveryProtocolIncomePage,
  PaymentCashflowArticlesPage,
  PaymentExpenseArticleFormPage,
  PaymentExpenseArticlesPage,
  ProductAvailabilitiesPage,
  ProductCapitalizationsPage,
  ProductSpecificationCodesPage,
  SupplyReturnsPage,
  SupplyUkraineDirectOrderCreatePage,
  SupplyUkraineDirectOrderDetailPage,
  SupplyUkraineDirectOrderInvoicesPage,
  SupplyUkraineDirectOrderProductIncomePage,
  SupplyUkraineDirectOrderSpecificationsPage,
  SupplyUkraineOrderOverviewPage,
  SupplyUkraineOrdersPage,
  ProductGroupDetailPage,
  ProductGroupsPage,
  ProductHistoryPage,
  ProductIncomeDocumentsPage,
  ProductIncomeUkrainePage,
  ProductPlacementsPage,
  ProductRemainsPage,
  ProductStoragesPage,
  ProductTransfersPage,
  ProductsPage,
  NewResalePage,
  NewUkraineSaleReturnPage,
  ReportsSalePage,
  ReportsStocksPage,
  ResalePage,
  ResalesPage,
  SadSpecificationsPage,
  SalesCockpitPage,
  SalesReturnClientPage,
  RetailClientSalesPage,
  RetailIncompleteSalePage,
  SalesOnlineShopPage,
  SalesUkrainePage,
  SalesDebtorsPage,
  SalesPreordersInterestPage,
  ShoppingCartReservePage,
  ClientProductMovementPage,
  OffersPage,
  SalesPredictionPage,
  SalesChartsPage,
  SupplyOrderProductPlacementPage,
  SupplyOrderUkraineProductPlacementPage,
  SupplierAccountingCashFlowPage,
  SupplierOrganizationCashFlowPage,
  SupplierOrganizationEditPage,
  SupplierOrganizationsPage,
  TaxFreeDocumentsPage,
  TaxFreeCarriersPage,
  TaxFreeCarrierFormPage,
  ActReconciliationsPage,
  ActReconciliationViewPage,
  SupplyUkrainePaymentProtocolsPage,
  TaxFreePackListsPage,
  SuppliersPage,
  TransportersPage,
  WarehouseUkrainePage,
  WarehouseUkraineOrderPlacementsPage,
  CompanyCarsPage,
  CompanyCarFormPage,
  CompanyCarRoadListsPage,
  CurrencyConvertorsPage,
  CurrencyConvertorFormPage,
  PaymentOnlineShopPage,
  BalancesPage,
  AvailablePaymentsPage,
  OutgoingCashflowCreatePage,
  AdvanceReportViewPage,
  UserEditPage,
  UserNewPage,
  UserRolesPage,
  UsersPage,
  VatReportsPage,
} from './lazyConsolePages'
import { lazyRoute } from './lazyRoute'
import { ProductCarouselDeepLinkRedirect } from './ProductCarouselDeepLinkRedirect'
import { SalesDashboardShell } from '../../shared/ui/SalesDashboardShell'

export type ConsoleRoute = {
  path: string
  element: ReactNode
}

const migratedConsoleRoutes: ConsoleRoute[] = [
  { path: '/', element: <Navigate to="/dashboard" replace /> },
  { path: '/dashboard', element: lazyRoute(<DashboardPage />) },
  { path: '/products', element: lazyRoute(<ProductsPage />) },
  { path: '/products/consignments/availabilities', element: lazyRoute(<ProductAvailabilitiesPage />) },
  { path: '/products/income/documents', element: lazyRoute(<ProductIncomeDocumentsPage />) },
  { path: '/products/income/ukraine', element: lazyRoute(<ProductIncomeUkrainePage />) },
  { path: '/products/placements', element: lazyRoute(<ProductPlacementsPage />) },
  { path: '/products/storages', element: lazyRoute(<ProductStoragesPage />) },
  { path: '/products/storages/incomes', element: lazyRoute(<ProductRemainsPage />) },
  { path: '/products/storages/incomes/:tab', element: lazyRoute(<ProductRemainsPage />) },
  { path: '/products/transfers', element: lazyRoute(<ProductTransfersPage />) },
  { path: '/products/capitalization', element: lazyRoute(<ProductCapitalizationsPage />) },
  { path: '/accounting/specification-codes', element: lazyRoute(<ProductSpecificationCodesPage />) },
  { path: '/accounting/specification-codes/uk', element: lazyRoute(<ProductSpecificationCodesPage />) },
  { path: '/supplies/returns', element: lazyRoute(<SupplyReturnsPage />) },
  { path: '/orders/ukraine/all', element: lazyRoute(<SupplyUkraineOrdersPage />) },
  { path: '/orders/ukraine/all/new', element: lazyRoute(<SupplyUkraineDirectOrderCreatePage />) },
  { path: '/orders/ukraine/view/:id', element: lazyRoute(<SupplyUkraineOrderOverviewPage />) },
  { path: '/orders/ukraine/placement/:id', element: lazyRoute(<WarehouseUkraineOrderPlacementsPage />) },
  { path: '/orders/ukraine/all/edit/:id/supply-invoices', element: lazyRoute(<SupplyUkraineDirectOrderInvoicesPage />) },
  { path: '/orders/ukraine/all/edit/:id/specifications', element: lazyRoute(<SupplyUkraineDirectOrderSpecificationsPage />) },
  { path: '/orders/ukraine/all/edit/:id/product-income', element: lazyRoute(<SupplyUkraineDirectOrderProductIncomePage />) },
  { path: '/orders/ukraine/all/edit/:id/new', element: lazyRoute(<SupplyUkraineDirectOrderDetailPage />) },
  { path: '/orders/ukraine/all/edit/:id', element: lazyRoute(<SupplyUkraineDirectOrderDetailPage />) },
  { path: '/orders/ukraine/:id/product-income', element: lazyRoute(<SupplyOrderUkraineProductPlacementPage />) },
  { path: '/orders/ukraine/protocols/:netid', element: lazyRoute(<SupplyUkrainePaymentProtocolsPage />) },
  { path: '/supply-orders/product-placement/:id', element: lazyRoute(<SupplyOrderProductPlacementPage />) },
  { path: '/orders/depreciated', element: lazyRoute(<DepreciatedOrdersPage />) },
  { path: '/product-delivery-protocols', element: lazyRoute(<ProductDeliveryProtocolsPage />) },
  { path: '/product-delivery-protocols/:id', element: lazyRoute(<ProductDeliveryProtocolLogisticPathPage />) },
  { path: '/product-delivery-protocols/:id/specifications', element: lazyRoute(<ProductDeliveryProtocolSpecificationPage />) },
  { path: '/product-delivery-protocols/:id/product-income', element: lazyRoute(<ProductDeliveryProtocolIncomePage />) },
  { path: '/products/history', element: lazyRoute(<ProductHistoryPage />) },
  { path: '/products/:netId', element: <ProductCarouselDeepLinkRedirect /> },
  { path: '/product-groups', element: lazyRoute(<ProductGroupsPage />) },
  { path: '/product-groups/:id', element: lazyRoute(<ProductGroupDetailPage />) },
  { path: '/transporters', element: lazyRoute(<TransportersPage />) },
  { path: '/warehouse/ukraine', element: lazyRoute(<WarehouseUkrainePage />) },
  { path: '/warehouse/ukraine/orders/:id/placements', element: lazyRoute(<WarehouseUkraineOrderPlacementsPage />) },
  { path: '/sales/cockpit', element: lazyRoute(<SalesCockpitPage />) },
]

const clientMigrationRoutes: ConsoleRoute[] = [
  { path: '/clients', element: lazyRoute(<ClientsPage />) },
  { path: '/clients/new/:step', element: lazyRoute(<ClientNewPage />) },
  { path: '/clients/new', element: lazyRoute(<ClientNewPage />) },
  { path: '/clients/edit/:netid/:step/:productNetId', element: lazyRoute(<ClientEditPage />) },
  { path: '/clients/edit/:netid/:step', element: lazyRoute(<ClientEditPage />) },
  { path: '/clients/edit/:netid', element: lazyRoute(<ClientEditPage />) },
  { path: '/clients/resources/:step', element: lazyRoute(<ClientResourcesPage />) },
  { path: '/clients/resources', element: lazyRoute(<ClientResourcesPage />) },
  { path: '/clients/accounting-cash-flow/:id', element: lazyRoute(<ClientAccountingCashFlowPage />) },
  { path: '/new-clients-from-ecommerce', element: lazyRoute(<NewEcommerceClientsPage />) },
  { path: '/clients-online-shop/client/:netUid', element: lazyRoute(<RetailClientSalesPage />) },
  { path: '/clients-online-shop/incomplete-sale/:netUid', element: lazyRoute(<RetailIncompleteSalePage />) },
  { path: '/clients-online-shop', element: lazyRoute(<OnlineShopClientsPage />) },
  { path: '/sales-online-shop', element: lazyRoute(<SalesOnlineShopPage />) },
  { path: '/incomplete-sales-online-shop', element: lazyRoute(<IncompleteSalesOnlineShopPage />) },
  { path: '/online-shop-cities', element: lazyRoute(<OnlineShopCitiesPage />) },
  { path: '/online-shop-seo', element: lazyRoute(<OnlineShopSeoPage />) },
  { path: '/suppliers', element: lazyRoute(<SuppliersPage />) },
  { path: '/suppliers/edit/:netid/:step/:productNetId', element: lazyRoute(<ClientEditPage />) },
  { path: '/suppliers/edit/:netid/:step', element: lazyRoute(<ClientEditPage />) },
  { path: '/suppliers/edit/:netid', element: lazyRoute(<ClientEditPage />) },
  { path: '/suppliers/accounting-cash-flow/:id', element: lazyRoute(<SupplierAccountingCashFlowPage />) },
  { path: '/organization-clients', element: lazyRoute(<OrganizationClientsPage />) },
  { path: '/organization-clients/new', element: lazyRoute(<OrganizationClientNewPage />) },
  { path: '/organization-clients/edit/:netId', element: lazyRoute(<OrganizationClientEditPage />) },
]

const userMigrationRoutes: ConsoleRoute[] = [
  { path: '/users', element: lazyRoute(<UsersPage />) },
  { path: '/users/new', element: lazyRoute(<UserNewPage />) },
  { path: '/users/edit/:netid', element: lazyRoute(<UserEditPage />) },
  { path: '/users/roles', element: lazyRoute(<UserRolesPage />) },
]

const accountingMigrationRoutes: ConsoleRoute[] = [
  { path: '/accounting/consumable-product', element: lazyRoute(<ConsumableProductsPage />) },
  { path: '/accounting/advanced-reports', element: lazyRoute(<AdvancedReportsPage />) },
  { path: '/accounting/consumable-services', element: lazyRoute(<AccountableExpensesPage />) },
  { path: '/accounting/consumable-orders', element: lazyRoute(<ConsumableOrdersPage />) },
  { path: '/accounting/consumable-orders/new', element: lazyRoute(<ConsumableOrderFormPage />) },
  { path: '/accounting/consumable-orders/edit/:id', element: lazyRoute(<ConsumableOrderFormPage />) },
  { path: '/accounting/consumable-orders/pay/:id', element: lazyRoute(<ConsumableOrderPayPage />) },
  { path: '/accounting/outgoing-cashflow', element: lazyRoute(<OutgoingCashflowsPage />) },
  { path: '/accounting/outgoing-cashflow/new', element: lazyRoute(<OutgoingCashflowCreatePage />) },
  { path: '/accounting/outgoing-cashflow/new/simple', element: lazyRoute(<OutgoingCashflowCreatePage />) },
  { path: '/accounting/outgoing-cashflow/new/supplier', element: lazyRoute(<OutgoingCashflowCreatePage />) },
  { path: '/accounting/outgoing-cashflow/new/client-return', element: lazyRoute(<OutgoingCashflowCreatePage />) },
  { path: '/accounting/outgoing-cashflow/new/group', element: lazyRoute(<OutgoingCashflowCreatePage />) },
  { path: '/accounting/outgoing-cashflow/new/payment-tasks', element: <Navigate to="/accounting/available-payments?type=2&operationType=4" replace /> },
  { path: '/accounting/outgoing-cashflow/:id/advanced-report/view', element: lazyRoute(<AdvanceReportViewPage />) },
  { path: '/accounting/storages', element: lazyRoute(<ConsumableStoragesPage />) },
  { path: '/accounting/storages/new', element: lazyRoute(<ConsumableStorageFormPage />) },
  { path: '/accounting/storages/edit/:id', element: lazyRoute(<ConsumableStorageFormPage />) },
  { path: '/accounting/supplier-organizations', element: lazyRoute(<SupplierOrganizationsPage />) },
  { path: '/accounting/supplier-organizations/new', element: lazyRoute(<SupplierOrganizationEditPage />) },
  { path: '/accounting/supplier-organizations/edit/:id', element: lazyRoute(<SupplierOrganizationEditPage />) },
  { path: '/accounting/supplier-organizations/cash-flow/:id', element: lazyRoute(<SupplierOrganizationCashFlowPage />) },
  { path: '/accounting/payment-cashflow-articles', element: lazyRoute(<PaymentCashflowArticlesPage />) },
  { path: '/accounting/payment-cashflow-articles/new', element: lazyRoute(<PaymentCashflowArticleFormPage />) },
  { path: '/accounting/payment-cashflow-articles/edit/:id', element: lazyRoute(<PaymentCashflowArticleFormPage />) },
  { path: '/accounting/income-cashflows', element: lazyRoute(<IncomeCashflowsPage />) },
  { path: '/accounting/income-cashflows/new', element: <Navigate to="/accounting/income-cashflows/new/conversion?type=0" replace /> },
  { path: '/accounting/income-cashflows/new/client', element: lazyRoute(<IncomeCashflowClientFormPage />) },
  { path: '/accounting/income-cashflows/new/conversion', element: lazyRoute(<IncomeCashflowConversionFormPage />) },
  { path: '/accounting/income-cashflows/new/shop', element: lazyRoute(<IncomeCashflowShopFormPage />) },
  { path: '/accounting/income-cashflows/new/user', element: lazyRoute(<IncomeCashflowUserFormPage />) },
  { path: '/accounting/income-cashflows/new/:step', element: <Navigate to="/accounting/income-cashflows" replace /> },
  { path: '/accounting/payment-expense-articles', element: lazyRoute(<PaymentExpenseArticlesPage />) },
  { path: '/accounting/payment-expense-articles/new', element: lazyRoute(<PaymentExpenseArticleFormPage />) },
  { path: '/accounting/payment-expense-articles/edit/:id', element: lazyRoute(<PaymentExpenseArticleFormPage />) },
  { path: '/accounting/payment-accounts', element: lazyRoute(<PaymentAccountsPage />) },
  { path: '/accounting/payment-accounts/new', element: lazyRoute(<PaymentAccountFormPage />) },
  { path: '/accounting/payment-accounts/edit/:id', element: lazyRoute(<PaymentAccountFormPage />) },
  { path: '/accounting/vat-reports', element: lazyRoute(<VatReportsPage />) },
  { path: '/accounting/advance-payments', element: lazyRoute(<AdvancePaymentsPage />) },
  { path: '/accounting/banks', element: lazyRoute(<AccountingBanksPage />) },
  { path: '/accounting/company-cars', element: lazyRoute(<CompanyCarsPage />) },
  { path: '/accounting/company-cars/new', element: lazyRoute(<CompanyCarFormPage />) },
  { path: '/accounting/company-cars/edit/:id', element: lazyRoute(<CompanyCarFormPage />) },
  { path: '/accounting/company-cars/:id/road-lists', element: lazyRoute(<CompanyCarRoadListsPage />) },
  { path: '/accounting/currency-convertors', element: lazyRoute(<CurrencyConvertorsPage />) },
  { path: '/accounting/currency-convertors/new', element: lazyRoute(<CurrencyConvertorFormPage />) },
  { path: '/accounting/currency-convertors/edit/:id', element: lazyRoute(<CurrencyConvertorFormPage />) },
  { path: '/accounting/payment-online-shop', element: lazyRoute(<PaymentOnlineShopPage />) },
  { path: '/accounting/sync/documents', element: lazyRoute(<BalancesPage />) },
  { path: '/accounting/available-payments', element: lazyRoute(<AvailablePaymentsPage />) },
  { path: '/payments/available', element: lazyRoute(<AvailablePaymentsPage />) },
]

const customsMigrationRoutes: ConsoleRoute[] = [
  { path: '/sad/all', element: lazyRoute(<AllSadsPage />) },
  { path: '/sad/edit/:netid', element: lazyRoute(<EditSadPage />) },
  { path: '/sad/edit/:netid/sale', element: lazyRoute(<EditSaleSadPage />) },
  { path: '/sad/edit/:netid/tir', element: lazyRoute(<EditTirSadPage />) },
  { path: '/sad/edit/:id/specifications', element: lazyRoute(<SadSpecificationsPage />) },
  { path: '/tax-free/pack-list/all', element: lazyRoute(<TaxFreePackListsPage />) },
  { path: '/tax-free/pack-list/edit/:id', element: lazyRoute(<EditTaxFreePackListPage />) },
  { path: '/tax-free/all', element: lazyRoute(<TaxFreeDocumentsPage />) },
  { path: '/tax-free/carriers/all', element: lazyRoute(<TaxFreeCarriersPage />) },
  { path: '/tax-free/carriers/new', element: lazyRoute(<TaxFreeCarrierFormPage />) },
  { path: '/tax-free/carriers/edit/:id', element: lazyRoute(<TaxFreeCarrierFormPage />) },
  { path: '/ukraine/act/reconcoliation', element: lazyRoute(<ActReconciliationsPage />) },
  { path: '/ukraine/act/reconcoliation/:netid', element: lazyRoute(<ActReconciliationViewPage />) },
]

const plannedConsoleRoutes: ConsoleRoute[] = [
  { path: '/act-providing-services', element: lazyRoute(<ActProvidingServicesPage />) },
  { path: '/act-providing-services/:id', element: lazyRoute(<ActProvidingServiceDetailPage />) },
  { path: '/basket-supply-ukraine-order', element: lazyRoute(<BasketSupplyUkraineOrderPage />) },
  { path: '/basket-supply-ukraine-order/*', element: lazyRoute(<BasketSupplyUkraineOrderPage />) },
  { path: '/recommendations', element: lazyRoute(<BasketSupplyUkraineOrderPage />) },
  { path: '/resales', element: lazyRoute(<ResalesPage />) },
  { path: '/resales/new', element: lazyRoute(<NewResalePage />) },
  { path: '/resales/:id', element: lazyRoute(<ResalePage />) },
  { path: '/reports/stocks', element: lazyRoute(<ReportsStocksPage />) },
  { path: '/reports/sale', element: lazyRoute(<ReportsSalePage />) },
  { path: '/sales/return/client', element: <SalesDashboardShell>{lazyRoute(<SalesReturnClientPage />)}</SalesDashboardShell> },
  { path: '/sales/ukraine/all', element: <SalesDashboardShell>{lazyRoute(<SalesUkrainePage />)}</SalesDashboardShell> },
  { path: '/sales/ukraine/debtors', element: <SalesDashboardShell>{lazyRoute(<SalesDebtorsPage />)}</SalesDashboardShell> },
  { path: '/sales/ukraine/interest', element: <SalesDashboardShell>{lazyRoute(<SalesPreordersInterestPage />)}</SalesDashboardShell> },
  { path: '/sales/ukraine/cart-reserve', element: <SalesDashboardShell>{lazyRoute(<ShoppingCartReservePage />)}</SalesDashboardShell> },
  { path: '/sales/ukraine/client-product-movement', element: <SalesDashboardShell>{lazyRoute(<ClientProductMovementPage />)}</SalesDashboardShell> },
  { path: '/sales/ukraine/offers', element: <SalesDashboardShell>{lazyRoute(<OffersPage />)}</SalesDashboardShell> },
  { path: '/sales/ukraine/prediction', element: <SalesDashboardShell>{lazyRoute(<SalesPredictionPage />)}</SalesDashboardShell> },
  { path: '/sales/charts', element: <SalesDashboardShell>{lazyRoute(<SalesChartsPage />)}</SalesDashboardShell> },
  { path: '/sales/ukraine/all/returns/new', element: <SalesDashboardShell>{lazyRoute(<NewUkraineSaleReturnPage />)}</SalesDashboardShell> },
  { path: '/sales', element: lazyRoute(<BasketSupplyUkraineOrderPage />) },
  { path: '/service/organisations', element: lazyRoute(<OrganisationServicesPage />) },
  { path: '/supply', element: <ModulePage module="Постачання" /> },
  { path: '/routes', element: <ModulePage module="Маршрути" /> },
  { path: '/settings', element: <ModulePage module="Налаштування" /> },
]

export const consoleRoutes: ConsoleRoute[] = [
  ...migratedConsoleRoutes,
  ...clientMigrationRoutes,
  ...userMigrationRoutes,
  ...accountingMigrationRoutes,
  ...customsMigrationRoutes,
  ...plannedConsoleRoutes,
]
