import {
  IconActivity,
  IconAddressBook,
  IconAdjustments,
  IconAlertCircle,
  IconAlertTriangle,
  IconArchive,
  IconArrowsExchange,
  IconArrowsLeftRight,
  IconAward,
  IconBook,
  IconBox,
  IconBuilding,
  IconBuildingBank,
  IconBuildingCommunity,
  IconBuildingFactory2,
  IconBuildingStore,
  IconBuildingWarehouse,
  IconBus,
  IconCalculator,
  IconCalendar,
  IconCalendarStats,
  IconCar,
  IconCash,
  IconCashBanknote,
  IconCategory2,
  IconChartBar,
  IconChartLine,
  IconChartPie,
  IconChecklist,
  IconBolt,
  IconBookmark,
  IconCloud,
  IconCompass,
  IconCube,
  IconDiamond,
  IconFlag,
  IconHash,
  IconHexagon,
  IconLayoutGrid,
  IconLeaf,
  IconRocket,
  IconSparkles,
  IconStar,
  IconTarget,
  IconClipboardCheck,
  IconClipboardList,
  IconClock,
  IconCode,
  IconCoin,
  IconCurrencyDollar,
  IconDatabase,
  IconDiscount2,
  IconFileDescription,
  IconFileExport,
  IconFileImport,
  IconFileInvoice,
  IconFileText,
  IconFolder,
  IconHelpCircle,
  IconHistory,
  IconId,
  IconKey,
  IconLayoutDashboard,
  IconList,
  IconLock,
  IconMail,
  IconMap2,
  IconMapPin,
  IconMessageCircle,
  IconNotes,
  IconPackage,
  IconPackageImport,
  IconPackages,
  IconPalette,
  IconPhone,
  IconPlug,
  IconPlus,
  IconPrinter,
  IconReceipt,
  IconReceipt2,
  IconReceiptRefund,
  IconReceiptTax,
  IconRefresh,
  IconReport,
  IconReportMoney,
  IconRoute,
  IconScale,
  IconScript,
  IconSearch,
  IconSettings,
  IconShield,
  IconShieldCheck,
  IconShoppingBag,
  IconShoppingCart,
  IconSpeakerphone,
  IconStack2,
  IconTag,
  IconTags,
  IconTemplate,
  IconTransferIn,
  IconTransferOut,
  IconTrendingDown,
  IconTrendingUp,
  IconTruck,
  IconTruckDelivery,
  IconTruckLoading,
  IconUser,
  IconUserCheck,
  IconUserCog,
  IconUserPlus,
  IconUsers,
  IconUsersGroup,
  IconWallet,
  IconWorld,
} from '@tabler/icons-react'
import type { ComponentType } from 'react'

type IconComponent = ComponentType<{ size?: number | string; stroke?: number | string; className?: string }>

const iconRules: { match: RegExp; icon: IconComponent }[] = [
  { match: /дашборд|головна|робоч.*простір/i, icon: IconLayoutDashboard },

  { match: /клієнт.онлайн|онлайн.?магазин/i, icon: IconShoppingBag },
  { match: /нов.*клієнт|створ.*клієнт|клієнт.*створ/i, icon: IconUserPlus },
  { match: /редагуванн.*клієнт|клієнт.*редагуванн/i, icon: IconUserCheck },
  { match: /реєстр.*клієнт|клієнт|контрагент/i, icon: IconUsers },
  { match: /виробник|фабрик|завод|manufactur/i, icon: IconBuildingFactory2 },
  { match: /постачальник/i, icon: IconTruckDelivery },
  { match: /постачанн/i, icon: IconTruck },
  { match: /відванта|відгрузк|логістик/i, icon: IconTruckLoading },
  { match: /доставк|delivery/i, icon: IconPackageImport },

  { match: /залишк|інвентар/i, icon: IconStack2 },
  { match: /склад|warehouse/i, icon: IconBuildingWarehouse },

  { match: /маршрут/i, icon: IconRoute },
  { match: /карт.|геолок|місцезнах/i, icon: IconMap2 },
  { match: /адрес/i, icon: IconMapPin },
  { match: /регіон|country|країн/i, icon: IconWorld },
  { match: /філі|відділенн|підрозділ/i, icon: IconBuildingCommunity },
  { match: /офіс|будівл|приміщенн/i, icon: IconBuilding },

  { match: /дозвіл|право доступ|permission/i, icon: IconShield },
  { match: /безпек|пароль|security/i, icon: IconLock },
  { match: /рол.|role/i, icon: IconKey },
  { match: /адмін|admin/i, icon: IconUserCog },
  { match: /верифікац|підтверджен|verif/i, icon: IconShieldCheck },
  { match: /сертифікат|ліцензі|certificate/i, icon: IconId },

  { match: /кошик|корзин/i, icon: IconShoppingCart },

  { match: /повернен/i, icon: IconReceiptRefund },
  { match: /прихідн|оприходуванн|надходженн/i, icon: IconTransferIn },
  { match: /видатков|видач/i, icon: IconTransferOut },
  { match: /переміщ/i, icon: IconArrowsExchange },
  { match: /акт.*звірк|звірк|ревізі/i, icon: IconClipboardCheck },
  { match: /акт.*списанн|акт.*оприход|акт.?/i, icon: IconChecklist },
  { match: /списанн/i, icon: IconReceipt2 },

  { match: /взаєморозрахунк|розрахунк|дебіторк|кредиторк/i, icon: IconScale },
  { match: /нез.ясован|невідом|невизначен/i, icon: IconHelpCircle },

  { match: /експорт|export|вигрузк|вивантаженн/i, icon: IconFileExport },
  { match: /імпорт|import|завантаженн.?файл|загрузк/i, icon: IconFileImport },
  { match: /договір|контракт|угод/i, icon: IconFileDescription },
  { match: /накладн|рахунок-факт|інвойс/i, icon: IconFileInvoice },
  { match: /рахунк/i, icon: IconFileInvoice },
  { match: /чек|квитанц/i, icon: IconReceipt },
  { match: /шаблон|template/i, icon: IconTemplate },
  { match: /прим.рк|copy|друк/i, icon: IconPrinter },
  { match: /документ/i, icon: IconFileText },
  { match: /файл|папк|folder|file/i, icon: IconFolder },
  { match: /нотатк|note|комент/i, icon: IconNotes },
  { match: /журнал|protocol|протокол/i, icon: IconBook },
  { match: /скрипт|формул|вираз/i, icon: IconScript },

  { match: /податк|акциз|tax/i, icon: IconReceiptTax },
  { match: /зарплат/i, icon: IconReportMoney },
  { match: /виплат|оплат|платіж/i, icon: IconCashBanknote },
  { match: /касов|каса/i, icon: IconCash },
  { match: /банк/i, icon: IconBuildingBank },
  { match: /ордер/i, icon: IconClipboardList },
  { match: /грош|кошт|готівк|бюджет/i, icon: IconWallet },
  { match: /курс|валют/i, icon: IconCurrencyDollar },
  { match: /монет|coin/i, icon: IconCoin },
  { match: /калькулят|обчисл|розрахун.*цін/i, icon: IconCalculator },
  { match: /прибут|дохід|profit|revenue/i, icon: IconTrendingUp },
  { match: /збитк|витрат|loss|expense/i, icon: IconTrendingDown },
  { match: /брак|дефект|defect|псуван/i, icon: IconAlertTriangle },

  { match: /авто|машин|транспорт|vehicle|car/i, icon: IconCar },
  { match: /автобус|bus|перевезен/i, icon: IconBus },
  { match: /замовлен|заявк|order/i, icon: IconClipboardList },

  { match: /товар|номенклатур|продукт|product/i, icon: IconPackage },
  { match: /категорі|групи|групп|category/i, icon: IconCategory2 },
  { match: /колекці|серії/i, icon: IconPackages },
  { match: /пакет/i, icon: IconBox },
  { match: /магазин|торгов|shop/i, icon: IconBuildingStore },
  { match: /продаж|sale/i, icon: IconTag },
  { match: /знижк|discount/i, icon: IconDiscount2 },
  { match: /акці.|прайс/i, icon: IconTags },
  { match: /бонус|лояльн|нагород|award/i, icon: IconAward },
  { match: /промо|маркетинг|реклам/i, icon: IconSpeakerphone },
  { match: /дизайн|оформленн|стил/i, icon: IconPalette },

  { match: /звіт|report/i, icon: IconReport },
  { match: /аналітик|статист/i, icon: IconChartBar },
  { match: /прогноз|forecast|тренд|trend/i, icon: IconChartLine },
  { match: /діаграм|graf|графік(?!.*раб|.*роб)/i, icon: IconChartPie },

  { match: /синхр/i, icon: IconRefresh },
  { match: /база.?дан|database/i, icon: IconDatabase },
  { match: /інтеграц|api|підключенн|integration/i, icon: IconPlug },
  { match: /розробк|разработ|developer|code/i, icon: IconCode },
  { match: /архів/i, icon: IconArchive },
  { match: /історі|history|log/i, icon: IconHistory },

  { match: /кален|розклад|schedule/i, icon: IconCalendar },
  { match: /таймлайн|період|план|year|місяц|тижд/i, icon: IconCalendarStats },
  { match: /час|таймер|годин/i, icon: IconClock },

  { match: /email|e-mail|пошт|mail/i, icon: IconMail },
  { match: /телефон|дзвінк|phone|call/i, icon: IconPhone },
  { match: /чат|messag|повідомленн.*чат|sms/i, icon: IconMessageCircle },
  { match: /контакт|address.?book/i, icon: IconAddressBook },

  { match: /пошук|search|фільтр/i, icon: IconSearch },
  { match: /налаштуванн|параметр|конфіг|setting/i, icon: IconSettings },
  { match: /контроль|регулюванн/i, icon: IconAdjustments },
  { match: /моніторинг|статус|стан/i, icon: IconActivity },
  { match: /сповіщенн|повідомленн|нотифікац|alert/i, icon: IconAlertCircle },

  { match: /кадр|hr|персонал|відділ.*кадр/i, icon: IconUsersGroup },
  { match: /реєстр|перелік|список|каталог/i, icon: IconList },

  { match: /користувач|user|працівник|співробітник|employee/i, icon: IconUser },
  { match: /обмін|exchange/i, icon: IconArrowsLeftRight },

  { match: /нов.|створ|new|add/i, icon: IconPlus },
]

const fallbackIcons: IconComponent[] = [
  IconHexagon,
  IconBookmark,
  IconFlag,
  IconTarget,
  IconCompass,
  IconHash,
  IconLayoutGrid,
  IconRocket,
  IconStar,
  IconSparkles,
  IconBolt,
  IconCloud,
  IconDiamond,
  IconLeaf,
  IconCube,
]

function hashString(value: string): number {
  let hash = 0
  for (let index = 0; index < value.length; index += 1) {
    hash = (hash << 5) - hash + value.charCodeAt(index)
    hash |= 0
  }
  return Math.abs(hash)
}

export function getNodeIcon(node: { Module?: string; Route?: string }): IconComponent {
  const text = `${node.Module ?? ''} ${node.Route ?? ''}`.toLowerCase()
  for (const rule of iconRules) {
    if (rule.match.test(text)) return rule.icon
  }
  return fallbackIcons[hashString(text) % fallbackIcons.length]
}
